apiVersion: v1
items:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: dynomite
    labels:
      app: dynomite
  spec:
    # note that name to setup service below
    serviceName: "dynomite"
    replicas: 3
    template:
      metadata:
        labels:
          app: dynomite
          deploymentconfig: dynomite
        annotations:
          pod.alpha.kubernetes.io/initialized: "true"
      spec:
        containers:
          - image: smilelab/dagota:latest
            name: dagota
            env:
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
              # note that name to setup service below
              - name: DYN_SVC
                value: dynomite
          - image: smilelab/dynomite:latest
            name: dynomite
            ports:
            - containerPort: 6379
              protocol: TCP
          - image: redis
            name: redis
            command:
              - "redis-server"
              - "--port"
              - "22122"
              - "--protected-mode"
              - "no"
            ports:
              - containerPort: 22122
                protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    creationTimestamp: null
    labels:
      app: dynomite
    # that name should be the same as
    # in serviceName in statefulset above
    name: dynomite
  spec:
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    # IMPORTANT, clusterIP to NONE
    clusterIP: None
    selector:
      app: dynomite
      deploymentconfig: dynomite
kind: List
metadata: {}

