apiVersion: v1
items:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: dynomite
    labels:
      app: dynomite
  spec:
    # note that name to setup service below
    serviceName: "dynomite"
    replicas: 3
    template:
      metadata:
        labels:
          app: dynomite
          deploymentconfig: dynomite
        annotations:
          pod.alpha.kubernetes.io/initialized: "true"
      spec:
        containers:
          - image: smilelab/dagota
            name: dagota
            env:
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
              # note that name to setup service below
              - name: DYN_SVC
                value: dynomite
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10

          - image: smilelab/dynomite:latest
            name: dynomite
            ports:
            - containerPort: 6379
              protocol: TCP
            readinessProbe:
              tcpSocket:
                port: 6379
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              tcpSocket:
                port: 6379
              initialDelaySeconds: 5
              periodSeconds: 10

          - image: redis 
            name: redis
            command:
              - "redis-server"
              - "--port"
              - "22122"
              - "--protected-mode"
              - "no"
            ports:
              - containerPort: 22122
                protocol: TCP
            readinessProbe:
              tcpSocket:
                port: 22122
            livenessProbe:
              exec:
                command:
                  - "redis-cli"
                  - "-p"
                  - "22122"
                  - "ping"
              initialDelaySeconds: 5
              periodSeconds: 10
            volumeMounts:
              - name: redis-data
                mountPath: /data
    volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    creationTimestamp: null
    labels:
      app: dynomite
    # that name should be the same as
    # in serviceName in statefulset above
    name: dynomite
  spec:
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    # IMPORTANT, clusterIP to NONE
    clusterIP: None
    selector:
      app: dynomite
      deploymentconfig: dynomite
kind: List
metadata: {}

